tasks:
  - npm install
  - npm test
  - node_modules/.bin/istanbul report cobertura
  - make jshint
  - make jscs

coverage:
  path: coverage/cobertura-coverage.xml
  parser: cobertura

services:
  - redis-server
